#!/usr/bin/env bash
# job-count.sh -- how many suites a parallel test runner runs at once. Sourced by tests/run-all.sh
# and bin/test-affected, so both share one default and one cap.
#
#   source tests/lib/job-count.sh; JOBS="$(job_count "$RUN_ALL_JOBS")"
#
# job_count <requested>: a number is used as is; `auto` or an empty value picks the platform
# default (macOS: the core count capped at 4; elsewhere: 1; see below).

_cores() {
  if command -v nproc >/dev/null 2>&1; then nproc
  elif command -v sysctl >/dev/null 2>&1; then sysctl -n hw.ncpu
  else echo 2
  fi
}
# DEFAULT IS 1 ON LINUX: parallel execution is opt-in via RUN_ALL_JOBS there until
# the ubuntu flake below is understood. macOS defaults to auto: every macOS run of
# the parallel batch, CI and local, has been green, and the flake has never shown
# on a Mac, so the platform where the evidence holds gets the 2.3x.
#
# Parallel runs are 2.3x faster and were green on a full dispatched matrix, on
# every macOS run, and on the PR runs. They then failed twice on master, on
# ubuntu only, on a DIFFERENT suite each time: first test-runs-dashboard, then
# test-understanding-wiring, each on one assertion out of twenty-odd green ones.
# (The failing assertion text is deliberately NOT quoted here: docs/FEATURES.md
# is generated by scanning test files for feature names, so quoting an assertion
# wires this runner to whatever feature it mentions and breaks the freshness
# pin. Read the two commits for the exact wording.)
# Both are content greps over files IN THE REPO, and both suites pass alone,
# pass sequentially, and pass on macOS. Marking each one serial as it appeared
# just moved the failure to the next suite, so the cause is shared, not local to
# either file. The open hypothesis is that some suite rewrites a repo-tracked
# file in place for the length of an assertion, which a concurrent reader then
# greps mid-write. Until that is found and fixed, the default stays sequential.
#
# The kept machinery is not dead weight: it is what the investigation needs, and
# RUN_ALL_JOBS=4 reproduces the failure. RUN_ALL_JOBS=auto picks the capped core
# count, which is what the default will go back to once the flake is fixed. The
# cap is 4, not the core count: the heaviest suites spawn 100-800 subprocesses
# each, so one worker per core oversubscribes the box several times over. At -P
# 10 on a 10-core M4, three suites blew past the 300s ceiling.
job_count() {
  local jobs="${1:-}"
  if [ -z "$jobs" ]; then
    case "$(uname -s)" in Darwin) jobs=auto ;; *) jobs=1 ;; esac
  fi
  if [ "$jobs" = "auto" ]; then
    jobs="$(_cores)"
    [ "$jobs" -gt 4 ] && jobs=4
  fi
  printf '%s\n' "$jobs"
}
